[package]
name = "node"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { version = "0.56", features = ["tcp","tokio","dns","websocket","quic","identify","ping","macros","yamux","tls","noise","request-response","json"] }
tokio = { version = "1", features = ["rt-multi-thread","macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1"

core = { path = "../core" }
libp2p-request-response = "0.29.0"
